fix IndexOutOfRangeException in inventory
Sometimes made items blink when scrolling lists because the list was
only partially refreshed (Draw() interrupted half way). This was self
healing few frames later when animationFrame was back in valid range.

IndexOutOfRangeException: Array index is out of range.
  at DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent.Draw ()
[0x00000] in <filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.Button.Draw () [0x00000] in
<filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
  at DaggerfallWorkshop.Game.UserInterface.UserInterfaceWindow.Draw ()
[0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallBaseWindow.Draw
() [0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallPopupWindow.Draw
() [0x00000] in <filename unknown>:0
  at DaggerfallWorkshop.Game.DaggerfallUI.OnGUI () [0x00000] in
<filename unknown>:0