fix missing InvariantCultures in ModSettings
Join correctly writes lists of values with InvariantCulture, but
TrySplit does not, leading to parse errors:

Failed to split values from 0.65,1.05
System.FormatException: Unknown char: .
  at System.Double.Parse (System.String s, NumberStyles style,
IFormatProvider provider) [0x00000] in <filename unknown>:0
  at System.Single.Parse (System.String s, IFormatProvider provider)
[0x00000] in <filename unknown>:0
  at System.Convert.ToSingle (System.String value, IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.String.System.IConvertible.ToSingle (IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.Convert.ToType (System.Object value, System.Type
conversionType, IFormatProvider provider, Boolean try_target_to_type)
[0x00000] in <filename unknown>:0
  at System.Convert.ChangeType (System.Object value, System.Type
conversionType) [0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.Utility.ModSupport.ModSettings.Key.TrySplit[Single]
(System.String input, Int32 count, System.Single[]& items) [0x00000] in
<filename unknown>:0

(Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

Failed to split values from 0.8,1
System.FormatException: Unknown char: .
  at System.Double.Parse (System.String s, NumberStyles style,
IFormatProvider provider) [0x00000] in <filename unknown>:0
  at System.Single.Parse (System.String s, IFormatProvider provider)
[0x00000] in <filename unknown>:0
  at System.Convert.ToSingle (System.String value, IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.String.System.IConvertible.ToSingle (IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.Convert.ToType (System.Object value, System.Type
conversionType, IFormatProvider provider, Boolean try_target_to_type)
[0x00000] in <filename unknown>:0
  at System.Convert.ChangeType (System.Object value, System.Type
conversionType) [0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.Utility.ModSupport.ModSettings.Key.TrySplit[Single]
(System.String input, Int32 count, System.Single[]& items) [0x00000] in
<filename unknown>:0

(Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

Failed to split values from 0.1,0.9
System.FormatException: Unknown char: .
  at System.Double.Parse (System.String s, NumberStyles style,
IFormatProvider provider) [0x00000] in <filename unknown>:0
  at System.Single.Parse (System.String s, IFormatProvider provider)
[0x00000] in <filename unknown>:0
  at System.Convert.ToSingle (System.String value, IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.String.System.IConvertible.ToSingle (IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.Convert.ToType (System.Object value, System.Type
conversionType, IFormatProvider provider, Boolean try_target_to_type)
[0x00000] in <filename unknown>:0
  at System.Convert.ChangeType (System.Object value, System.Type
conversionType) [0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.Utility.ModSupport.ModSettings.Key.TrySplit[Single]
(System.String input, Int32 count, System.Single[]& items) [0x00000] in
<filename unknown>:0

(Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

Failed to split values from 0.2,0.6
System.FormatException: Unknown char: .
  at System.Double.Parse (System.String s, NumberStyles style,
IFormatProvider provider) [0x00000] in <filename unknown>:0
  at System.Single.Parse (System.String s, IFormatProvider provider)
[0x00000] in <filename unknown>:0
  at System.Convert.ToSingle (System.String value, IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.String.System.IConvertible.ToSingle (IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.Convert.ToType (System.Object value, System.Type
conversionType, IFormatProvider provider, Boolean try_target_to_type)
[0x00000] in <filename unknown>:0
  at System.Convert.ChangeType (System.Object value, System.Type
conversionType) [0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.Utility.ModSupport.ModSettings.Key.TrySplit[Single]
(System.String input, Int32 count, System.Single[]& items) [0x00000] in
<filename unknown>:0

(Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

Failed to split values from 0.1,0.8
System.FormatException: Unknown char: .
  at System.Double.Parse (System.String s, NumberStyles style,
IFormatProvider provider) [0x00000] in <filename unknown>:0
  at System.Single.Parse (System.String s, IFormatProvider provider)
[0x00000] in <filename unknown>:0
  at System.Convert.ToSingle (System.String value, IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.String.System.IConvertible.ToSingle (IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.Convert.ToType (System.Object value, System.Type
conversionType, IFormatProvider provider, Boolean try_target_to_type)
[0x00000] in <filename unknown>:0
  at System.Convert.ChangeType (System.Object value, System.Type
conversionType) [0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.Utility.ModSupport.ModSettings.Key.TrySplit[Single]
(System.String input, Int32 count, System.Single[]& items) [0x00000] in
<filename unknown>:0

(Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

Failed to split values from 0,1.1
System.FormatException: Unknown char: .
  at System.Double.Parse (System.String s, NumberStyles style,
IFormatProvider provider) [0x00000] in <filename unknown>:0
  at System.Single.Parse (System.String s, IFormatProvider provider)
[0x00000] in <filename unknown>:0
  at System.Convert.ToSingle (System.String value, IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.String.System.IConvertible.ToSingle (IFormatProvider
provider) [0x00000] in <filename unknown>:0
  at System.Convert.ToType (System.Object value, System.Type
conversionType, IFormatProvider provider, Boolean try_target_to_type)
[0x00000] in <filename unknown>:0
  at System.Convert.ChangeType (System.Object value, System.Type
conversionType) [0x00000] in <filename unknown>:0
  at
DaggerfallWorkshop.Game.Utility.ModSupport.ModSettings.Key.TrySplit[Single]
(System.String input, Int32 count, System.Single[]& items) [0x00000] in
<filename unknown>:0

Other issue is related to float tuples deserialization; For example
ConvenientClock allows to set clock scale, correctly write this setting
in InvariantCulture format, but is not restored in game (clock stays at
its nominal size).